app_homepage:
    path: /
    defaults:
        _controller: 'AppBundle:Default:homepage'

app_churro_time_entry_list:
    path: /time-entries
    defaults:
        _controller: 'AppBundle:ChurroTimeEntry:list'

app_churro_time_entry_create:
    path: /time-entries/create
    defaults:
        _controller: 'AppBundle:ChurroTimeEntry:create'

app_churro_time_entry_item:
    path: /time-entries/{id}
    defaults:
        _controller: 'AppBundle:ChurroTimeEntry:item'